-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg9/scGnrJ0YfbY2GJ
KLS6XlYfdgKKHnHaKfMVAXlzy2qgCgYIKoZIzj0DAQehRANCAASafMi1wust0KzV
gisgk+JaCjTbvvS4i4b32KNusH6YaNBqcgqIxdlTl0mzdTxLTyuw6beUKBMjhtCO
5ZnSZ+9J
-----END PRIVATE KEY-----